### ISSUE TITLE
Include trailing commas when highlighting `STSSelectParentNode` - Lua

### ISSUE THREAD

**Issue by jay-babu** [ziontee113/syntax-tree-surfer#10]
Hello,

When I call `STSSelectParentNode`, it highlights the current node, but for some reason doesn't include the comma at the end when it is (I think) part of the node as shown in the screenshot. I was wondering if it is possible to somehow include when selecting.

![image](https://user-images.githubusercontent.com/36803168/188257092-5e42d2c5-6f38-4cc3-a151-86739e472937.png)

**Comment by jay-babu** [comment]
Line 69 is highlighted with the comma being included

**Comment by ziontee113** [comment]
HI @jayp0521, commas `,` are their own kind of node. It's not part of the node you're selecting. If you have TreesitterPlayground, open it up and press `a`, you'll see what I mean.
You can still swap nodes without selecting the `,`.
