### ISSUE TITLE
Markdown inline_link doesn't work

### ISSUE THREAD

**Issue by avucic** [ziontee113/syntax-tree-surfer#13]
I'm trying to use `filtered_jump` to jump to `inline_link` in markdown file but it doesn't work. I can use any other syntax like comment, paragraph...but links don't work. Is this maybe related to splitting tree-sitter to`markdown` and `markdown_inline` queries? 

At some point, before I updated my plugins it was working...

**Comment by ziontee113** [comment]
Hi @avucic , Syntax Tree Surfer didn't have any new update for a while. It's probably the markdown syntax, which I don't have any control over.

Sorry about your inconvenience.

**Comment by avucic** [comment]
@ziontee113 Thanks. Then I'll close this issue.
