### ISSUE TITLE
How do you get the AST highlighted in visual mode like in the demo video?

### ISSUE THREAD

**Issue by llllvvuu** [ziontee113/syntax-tree-surfer#16]
https://github.com/ziontee113/syntax-tree-surfer#navigate-around-your-document-based-on-treesitters-abstract-syntax-tree-step-into-step-out-step-over-step-back it's show when `random_array` is highlighted

Mine just looks like this:

https://github.com/ziontee113/syntax-tree-surfer/assets/5601392/25b7782c-797e-44bb-9214-349d0e64f10f

**Comment by ziontee113** [comment]
You can use

```lua
-- Visual Selection from Normal Mode
vim.keymap.set("n", "vx", '<cmd>STSSelectMasterNode<cr>', opts)
vim.keymap.set("n", "vn", '<cmd>STSSelectCurrentNode<cr>', opts)```

to achieve that.

**Comment by llllvvuu** [comment]
So it's supposed to show the AST indicators when pressing `vn` but not when pressing `V`?

Even with `STSSelectCurrentNode` I got only the selection/range but not the AST indicators. Do you know which part is repsonsible for those indicators?

I couldn't find it here:
https://github.com/ziontee113/syntax-tree-surfer/blob/8b707abc887379468086a4774b5d1a233d69b0c7/lua/syntax-tree-surfer/init.lua#L51-L64

EDIT: maybe just the colorscheme need to set bgcolor, let me try...

**Comment by llllvvuu** [comment]
OK, I figured it out, it's a feature of gruvbox: https://github.com/gruvbox-community/gruvbox/issues/126
