### ISSUE TITLE
Is it possible to jump to the next sibling from normal mode?

### ISSUE THREAD

**Issue by elmehalawi** [ziontee113/syntax-tree-surfer#7]
I love jumping around using this plugin with `vn` but sometimes it selects a node that is longer than the screen, and I can't see the top of it, which is where the definition is. Also, I would prefer to be in normal mode after finishing jumping so it's easier to go and edit things.

Is this something in the cards, or is it out of scope?

**Comment by ziontee113** [comment]
It is in the cards. Back then when I was making this plugin I didn't think about jumping around in normal mode. I should be able to add this feature when I get back from my break.

**Comment by elmehalawi** [comment]
That sounds great, really looking forward to it.

Really appreciate your work :)

**Comment by ziontee113** [comment]
Hi @elmehalawi , sorry for the delay :)

Now you can use these commands: `STSJumpToStartOfCurrentNode` and `STSJumpToEndOfCurrentNode`.

Also if you use `vn`, and it jumps you to the end of the node, you can press `o` to jump to the beginning of the selection.

**Comment by elmehalawi** [comment]
@ziontee113 Thank you so much for this :)
